### ISSUE TITLE
radicle-org-node gets stuck, ignoring traffic, spinning 2 cpu cores

### ISSUE THREAD

**Issue by kermit4** [radicle-dev/radicle-client-services#11]
netstat shows unread packets accumulating
top shows 200% CPU usage

the last line in logs was:

Aug 19 19:18:34.619 INFO ureq::unit: sending request POST https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs

this is at commit 0a4a3954684daea7693d385a2f902f34f4ecf766
release build

Linux 4.18.0-305.3.1.el8.x86_64
CentOS Linux release 8.4.2105

The CPU usage may be unrelated as it does that at times it is responding to network traffic.

@kim thinks it may be due to https://github.com/radicle-dev/radicle-link/issues/734

**Comment by kim** [comment]
Oh so _this_ is a radicle org node. Would capturing logs not suggest that #5, radicle-dev/radicle-link#734 and this one are related?

**Comment by cloudhead** [comment]
Yeah, they are all the same issue AFAICT.

**Comment by cloudhead** [comment]
I'd like to upgrade the seed node to the latest radicle-link, as well as the org node, and see if this is still an issue :thinking:

**Comment by kermit4** [comment]
I think it stopped leaking memory around the same time it began using a lot of CPU so I think #5 is fixed.

There's not much network traffic so I don't think it relates to https://github.com/radicle-dev/radicle-link/issues/734 either.

**Comment by kermit4** [comment]
For the hangs (probably unrelated to CPU usage) In at least 3 of 3 cases, the last line in logs is:

INFO ureq::unit: sending request POST https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs  


Maybe that request isn't spawning its own thread?

**Comment by kermit4** [comment]
Dropping traffic to api.thegraph.com didn't cause hangs so maybe not.  Maybe that's just the part that wasn't hung so is why it kept showing up in logs when nothing else was.

**Comment by kermit4** [comment]
For 30 minutes while the network receive queue was full, "INFO ureq::unit: sending request POST https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs" was the only line in the logs.

**Comment by cloudhead** [comment]
So what you're seeing now is:
* Normal memory consumption
* High CPU usage
* Normal network usage

Is that right?

**Comment by sebastinez** [comment]
Closing this issue since we deprecated the org-node some time ago.
