### ISSUE TITLE
Push failed fatal: repository 'https://<server>/<user>/' not found

### ISSUE THREAD

**Issue by christroutner** [radicle-dev/radicle-client-services#142]
I'm trying to set up a seed node for my organization. I've got a temporary server setup at bchd.nl, and when I push with this command:
- `rad push --seed bchd.nl`

I get this output:

```
!! Syncing delegate hnrknfg3orx71sf8k7yps9menjnthd87ymf5y...

== Push failed fatal: repository 'https://bchd.nl/hnrknfg3orx71sf8k7yps9menjnthd87ymf5y/' not found

```

I wasn't having any luck with caddy, so I got an SSL cert from Let's Encrypt for my bchd.nl domain and set up nginx to proxy SSL connections to port 8777, which is pointing at the `radicle-http-api` Docker container. I opened that port in the Docker container. [Here is my modified docker-compose file](https://github.com/christroutner/radicle-client-services/blob/b52c84e5e5726483002e3d39a3e3ff1651b33ebd/docker-compose.yml).

Do I need to open some additional ports? Like port 8778 for the git server?

It appears to me that the account needs to be created, and there is a good chance that something is configured incorrectly.

I'd really appreciate any guidance you can provide on how to resolve this error. It seems like I'm really close. I'd like to have this seed be open for anyone to push to it, just like the three Radicle seeds are now.

**Comment by christroutner** [comment]
@cloudhead what am I missing? Is this related to #117?

**Comment by cloudhead** [comment]
Perhaps you need to initialize the storage with the `service-init` crate? It would help to see the logs of the git server and http-api.

**Comment by sebastinez** [comment]
@christroutner Do you have any additional info on this issue? Have you tried with newer builds of the CLI or the client-services?

Else I would propose to close this issue, and eventually reopen if there is new information.

**Comment by christroutner** [comment]
This problem appears to have gone away with time. I have no idea what caused it, why it appeared on multiple seed servers at the same time, or why it went away.

Closing this issue.
