### ISSUE TITLE
http-api: Allow case-insensitive project alias queries

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-client-services#201]
Ok have thought about this a bit, and while we already do case-insensitive searches against ENS profiles (with room for improvement), I'm not sure that this is practical for projects, since we don't enforce users to only use lower case project names.

**Comment by cloudhead** [comment]
Yeah, aliases should be case-insensitive to prevent abuse.

**Comment by rudolfs** [comment]
> Not sure on the probability, but it could be a way to mislead people into a malicious copy of a repo.

Hmm, didn't think of this before 🤔 

So the way to trick someone would be to create another project with different casing and hoping that the user would pick the wrong one from the result list?

**Comment by sebastinez** [comment]
> So the way to trick someone would be to create another project with different casing and hoping that the user would pick the wrong one from the result list?

Sorry I meant the same thing as you, we should return both and let the user choose the right one.

For that I think we would need to edit the alias HashMap to use as key a lowercase representation of an alias and a vector of all URNs that have the same name case-insensitive.

wdyt @cloudhead

**Comment by cloudhead** [comment]
We don't need a vector, we just need to lowercase all the aliases. 1 alias = 1 project.

**Comment by sebastinez** [comment]
> We don't need a vector, we just need to lowercase all the aliases. 1 alias = 1 project.

This sounds easy to implement, but I feel like this will generate name collisions, since we could have multiple names with different casings, pointing to different URNs.

for example
```
radicle-interface    ->     rad:git:hnrkjajuucc6zp5eknt3s9xykqsrus44cjimy
Radicle-Interface   ->     rad:git:hnrk86sjyrxmt8nyqfd86ctudogdmphhg8f6y
```

But for the `http-api` it would save the first record and then omit the second one, since it would be the same lower cased name..

**Comment by sebastinez** [comment]
Superseded by https://github.com/radicle-dev/heartwood/issues/180
