### ISSUE TITLE
radicle-org-node memory leak

### ISSUE THREAD

**Issue by kermit4** [radicle-dev/radicle-client-services#5]
Memory usage climbs to 14GB or more at a rate of 3-5MB/s.

At commit e0de40bbff78a65ee5501952533e2083db909477 Date:   Tue Jul 20 11:36:09 2021 +0200

The following command

```
cargo run -p radicle-org-node -- \
  --root ~/.radicle \
  --subgraph 'https://api.thegraph.com/subgraphs/name/radicle-dev/radicle-orgs' \
  --orgs 0x34F2C1AC75d0627ab29E367718235d058D5FD88A \
  --identity ~/.radicle-seed/secret.key \
  --bootstrap 'hynkyndc6w3p8urucakobzna7sxwgcqny7xxtw88dtx3pkf7m3nrzc@sprout.radicle.xyz:12345'
```

using:
cargo 1.54.0-nightly (e51522ab3 2021-05-07)
rustc 1.54.0-nightly (881c1ac40 2021-05-08)
Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 8.4.2105

**Comment by kermit4** [comment]
I'm not sure if this is helpful:  [heap.pdf](https://github.com/radicle-dev/radicle-client-services/files/6858973/heap.pdf)

**Comment by cloudhead** [comment]
Thanks, will look into this!

**Comment by cloudhead** [comment]
Hmm, could you try running in release mode? Otherwise it's hard to tell if this is an issue in production.

`cargo run --release -p radicle-org-node -- ...

**Comment by kermit4** [comment]
Relaese build took 17 minutes once, and 26 minutes another time, to reach 2GB of  virtual memory size, at 1.3GB and 1GB of RSS respectively.

**Comment by kermit4** [comment]
Here's a minutely sample:

time pid VSZ RSS
2021-07-22T02:36:01 933 2233220 1106252 
2021-07-22T02:37:01 933 2233220 1123412 
2021-07-22T02:38:01 933 2233208 1123412 
2021-07-22T02:39:01 933 2167672 1109984 
2021-07-22T02:40:01 933 2167684 1109984 
2021-07-22T02:41:01 933 2167648 1109984 
2021-07-22T02:42:01 933 2167672 1109984 
2021-07-22T02:43:02 933 2167672 1075044 
2021-07-22T02:44:01 933 2167672 1075044 
2021-07-22T02:45:01 933 2167672 1075044 
2021-07-22T02:46:01 933 2167672 1075044 
2021-07-22T02:47:02 933 2102136 1032448 
2021-07-22T02:48:01 933 2102136 1032708 
2021-07-22T02:49:01 933 2102136 1041680 
2021-07-22T02:50:01 933 2102148 1057256 
2021-07-22T02:51:02 933 2694024 1588688 
2021-07-22T02:52:01 933 4596604 3158400 
2021-07-22T02:53:02 933 4596604 3201432 
2021-07-22T02:54:01 933 4596604 3228624 
2021-07-22T02:55:01 933 4592516 3251536 
2021-07-22T02:56:02 933 4592504 3254176 
2021-07-22T02:57:01 933 4592516 3281632 
2021-07-22T02:58:01 933 4592516 3298528 
2021-07-22T02:59:01 933 4592516 3330472 
2021-07-22T03:00:01 933 4592516 3331792 
2021-07-22T03:01:01 933 4592516 3352120 
2021-07-22T03:02:02 933 4592516 3364264 
2021-07-22T03:03:01 933 4658052 3515008 
2021-07-22T03:04:01 933 4985732 3768188 
2021-07-22T03:05:01 933 4920196 3779288 
2021-07-22T03:06:01 933 4920196 3779288 
2021-07-22T03:07:01 933 4920196 3772376 
2021-07-22T03:08:01 933 4920196 3772376

**Comment by kermit4** [comment]
A more dramatic event:

UTC pid  VSZ RSS
2021-07-22T04:28:01 20921 1577860 579964
2021-07-22T04:29:01 20921 1577860 580228
2021-07-22T04:30:01 20921 1577860 581548
2021-07-22T04:31:01 20921 1577860 581548
2021-07-22T04:32:01 20921 1577848 579184
2021-07-22T04:33:02 20921 2102148 987852
2021-07-22T04:34:01 20921 2890648 1676364
2021-07-22T04:35:01 20921 3349376 2063124
2021-07-22T04:36:01 20921 4071296 2697660
2021-07-22T04:37:01 20921 5054336 3489924
2021-07-22T04:38:02 20921 6233996 4519260
2021-07-22T04:39:01 20921 7545740 5604980

**Comment by cloudhead** [comment]
Thanks, I'm trying to reproduce this locally. Strangely it seems to take much more memory on your system than on mine:

```
Every 2.0s: VmRSS: 29268 kB
```

So only 29 MB, and this is with the debug build. It's been running for 20 mins so far..

**Comment by cloudhead** [comment]
if you do `export  RUST_LOG=org-node=debug` before running it, do you see any debug output during the memory hike?

**Comment by kermit4** [comment]
> Thanks, I'm trying to reproduce this locally. Strangely it seems to take much more memory on your system than on mine:

Are you behind NAT?  Mine isn't so maybe mine's getting traffic from random people not speaking the protocol, being simply port 8888.  Would it be safe to try changing the port?

**Comment by kermit4** [comment]
> > Thanks, I'm trying to reproduce this locally. Strangely it seems to take much more memory on your system than on mine:
> 
> Are you behind NAT? Mine isn't so maybe mine's getting traffic from random people not speaking the protocol, being simply port 8888. Would it be safe to try changing the port?

Oh that's not why, it's only talking to one host.

**Comment by kermit4** [comment]
> if you do `export RUST_LOG=org-node=debug` before running it, do you see any debug output during the memory hike?

Only "INFO org-node: Found 0 project(s)" as all times.

**Comment by cloudhead** [comment]
> Are you behind NAT? Mine isn't so maybe mine's getting traffic from random people not speaking the protocol, being simply port 8888. Would it be safe to try changing the port?

Could be, I just tried on my laptop. Yes, you can use any port you like.

**Comment by kermit4** [comment]
> > Are you behind NAT? Mine isn't so maybe mine's getting traffic from random people not speaking the protocol, being simply port 8888. Would it be safe to try changing the port?
> 
> Could be, I just tried on my laptop. Yes, you can use any port you like.


I changed the port but no one is talking to it now.  There were over a dozen before, most from port 12345.  It's not growing memory now though :-D

If you're behind NAT have you verified anyone's reaching your node?

**Comment by kermit4** [comment]
> > Are you behind NAT? Mine isn't so maybe mine's getting traffic from random people not speaking the protocol, being simply port 8888. Would it be safe to try changing the port?
> 
> Could be, I just tried on my laptop. Yes, you can use any port you like.

If you're behind NAT have you verified people are talking to your node (as it doesn't grow when no one's talking to it)?  I'm seeing 16 IPs.   It still grows with only the 12345 source ports now.

**Comment by kermit4** [comment]
I think the leak is in librad.  I'm trying to comment out sections of code until the leak goes away since there doesn't seem to be any way to dump a heap in Rust (unlike Ruby or Java) to simply look, but I can't get Cargo to use my copy of librad:

In org-node/Cargo.toml I tried:
librad = { path = "../../radicle-link/librad" }

But I get:

```
error[E0308]: mismatched types
   --> org-node/src/lib.rs:127:9
    |
127 |         paths,
    |         ^^^^^ expected struct `librad::paths::Paths`, found struct `radicle_daemon::Paths`
    |
    = note: perhaps two different versions of crate `librad` are being used?

error: aborting due to previous error


```

**Comment by kermit4** [comment]
This might show the issue but I couldn't get it to build:  https://github.com/rust-analyzer/rust-analyzer.github.io

https://rust-analyzer.github.io/blog/2020/12/04/measuring-memory-usage-in-rust.html

"It then traverses the graph of objects and computes how many instances of each object are there and how much memory they occupy. The profiler also tracks the ownership relations, to ferret out facts like “90% of strings in this program are owned by the Config struct”

**Comment by cloudhead** [comment]
Perhaps it would make sense to try with the latest librad master: `cargo update -p librad`

**Comment by kermit4** [comment]
> Perhaps it would make sense to try with the latest librad master: `cargo update -p librad`

Running that, then building and running a release version, it has grown to 5GB VSZ 4GB RSS in 1 hour.

I'd like to try commenting out different sections of librad to isolate where the memory is leaking (unless you know a way to profile the memory / dump the heap / list allocated objects) but am running into the error pasted earlier when trying to substitute the crate with a local copy.

**Comment by cloudhead** [comment]
Yes you need to use a `[patch]` section - check the root Cargo.toml, it has such a section - you should be able to change it there.

**Comment by kermit4** [comment]
What should put in the Cargo.toml to use a local copy of the librad repo (so I can isolate the memory leak)?  None of the combinations of modifying that, running cargo build, and running cargo update -p librad, that I've tried produce less errors than the paths error I pasted above.

**Comment by kermit4** [comment]
Changing the location of radicle-daemon to match fixed the conflict.  I'll be able to isolate the memory leak now.

**Comment by cloudhead** [comment]
Ah great, curious what you find. I wonder if it's related to https://github.com/radicle-dev/radicle-link/issues/734 ?

If you enable debug with `RUST_LOG=debug`, do you see lots of ingress streams?

**Comment by kermit4** [comment]
> Ah great, curious what you find. I wonder if it's related to [radicle-dev/radicle-link#734](https://github.com/radicle-dev/radicle-link/issues/734) ?

Thanks for the link.  And the DEBUG= tip.

> If you enable debug with `RUST_LOG=debug`, do you see lots of ingress streams?
Lots.
```
Jul 29 01:53:35.858  INFO accept{peer_id=hydskrqs59bacwb13aibhrfc76k34dcsjodecq19fwxswqacgdkxey}:incoming:incoming{remote_id=hyy4ebh8amk3ypyawgpjn
fpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote_addr=95.111.216.99:12345}: librad::net::protocol::io::streams: new ingress stream
Jul 29 01:53:35.905  INFO accept{peer_id=hydskrqs59bacwb13aibhrfc76k34dcsjodecq19fwxswqacgdkxey}:incoming:incoming{remote_id=hyy4ebh8amk3ypyawgpjn
fpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote_addr=95.111.216.99:12345}: librad::net::protocol::io::streams: new ingress stream 
Jul 29 01:53:36.037  INFO accept{peer_id=hydskrqs59bacwb13aibhrfc76k34dcsjodecq19fwxswqacgdkxey}:incoming:incoming{remote_id=hyy4ebh8amk3ypyawgpjn
fpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote_addr=95.111.216.99:12345}: librad::net::protocol::io::streams: new ingress stream 
Jul 29 01:53:36.074  INFO accept{peer_id=hydskrqs59bacwb13aibhrfc76k34dcsjodecq19fwxswqacgdkxey}:incoming:incoming{remote_id=hyy4ebh8amk3ypyawgpjn
fpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote_addr=95.111.216.99:12345}: librad::net::protocol::io::streams: new ingress stream
Jul 29 01:53:36.333  INFO accept{peer_id=hydskrqs59bacwb13aibhrfc76k34dcsjodecq19fwxswqacgdkxey}:incoming:incoming{remote_id=hyy4ebh8amk3ypyawgpjn
fpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote_addr=95.111.216.99:12345}: librad::net::protocol::io::streams: new ingress stream 
```

**Comment by kermit4** [comment]
Here's some data

lines of "new ingress", timestamp, memory size, total process CPU time
39        02:21:02  16016    0:03
68        02:22:01  13944    0:01   
266       02:23:01  14256    0:01   
5719      02:24:01  14832    0:01   
9685      02:25:01  20052    0:04   
2884      02:26:01  21108    0:09   
22735     02:27:01  47772    0:10   
17556     02:28:01  213348   0:32   
37769     02:29:01  261924   0:47   
4235      02:30:01  974920   1:15   
29406     02:31:01  1015132  2:07
29946     02:32:02  1053112  3:05
22505     02:33:01  1462156  3:37
16315     02:34:01  1853964  4:44
30186     02:35:01  2091036  5:51
34777     02:36:01  2606992  7:02
1953      02:37:01  3276988  8:27

so there's correlation, but being correlated to activity isn't a surprise.  Is that more than there should be of "new ingress streams" ?

**Comment by cloudhead** [comment]
> so there's correlation, but being correlated to activity isn't a surprise. Is that more than there should be of "new ingress streams" ?

Yeah, these are peers establishing connections over QUIC. In this case a single peer is establishing many connections. So it appears like the issues are related, since connections carry state.

**Comment by kermit4** [comment]
Probably not news but indeed if I comment out this entire match:

https://github.com/radicle-dev/radicle-link/blob/cb91ccdd07d08276112c876a670941f9be8f18ef/librad/src/net/protocol/io/streams.rs#L52

it stops leaking.  (Of course it stops doing much at all)

I'm running @kim's update that addressed the ingress stream frequency now and will let you know if it still leaks.

**Comment by kermit4** [comment]
So far its memory use has remained very low, however few hosts are communicating with it compared to when it was leaking.

**Comment by cloudhead** [comment]
So memory use is low, but CPU is high?

**Comment by sebastinez** [comment]
Hey @cloudhead I think this issue can be safely closed? Since we already deprecated the `org-node` some time ago.
