### ISSUE TITLE
[org-node] Need to announce peer update to the gossip protocol

### ISSUE THREAD

**Issue by Ryanmtate** [radicle-dev/radicle-client-services#56]
When the push is received, the ref is announced to the network. Currently, the org-node does not announce updates.

Gossip new ref.

- [ ] Add announcement on startup;
- [x] Add announcement on receive update from `git-server`;

**Comment by cloudhead** [comment]
Example here: https://github.com/radicle-dev/radicle-link/blob/master/daemon/src/peer/gossip.rs

**Comment by cloudhead** [comment]
Announcement on startup example here: https://github.com/radicle-dev/radicle-link/blob/master/daemon/src/peer/announcement.rs

**Comment by Ryanmtate** [comment]
Closed by #58
