### ISSUE TITLE
[git-server] support for SSH signing for commit/push in pre-receive hook

### ISSUE THREAD

**Issue by Ryanmtate** [radicle-dev/radicle-client-services#66]
Git 2.34 adds support for SSH signing for commit/push

Update pre-receive hook to allow for verifying signed SSH certificates for git push

See: 

- https://github.com/git/git/pull/1041
- https://www.agwa.name/blog/post/ssh_signatures

**Comment by cloudhead** [comment]
https://github.blog/2021-11-15-highlights-from-git-2-34/#tidbits

**Comment by cloudhead** [comment]
Done.
