### ISSUE TITLE
[git-server] Support project aliases

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-client-services#72]
Currently, pushing through the git bridge requires knowing the project id.

It would be nice if the bridge also supported pushing via the project's name, as specified in the project identity, eg.
```
git push https://seed.alt-clients.radicle.xyz/radicle-client-tools.git
```

Note that project names are not unique, so it's possible for there to be duplicates. This should be handled somehow, perhaps by not supporting aliases for projects with non-unique names.

**Comment by xphoniex** [comment]
How about keeping alias mappings in a flat file, read by both `git-server` and `http-api`?

> Note that project names are not unique, so it's possible for there to be duplicates.

Can you explain a case where there are duplicates for the same name?
